FROM node:18-alpine

ARG VOIP_KEY
ARG MAX_PARTICIPANTS
ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_PASSWORD
ARG PORT

ENV VOIP_KEY=$VOIP_KEY
ENV MAX_PARTICIPANTS=$MAX_PARTICIPANTS
ENV REDIS_HOST=$REDIS_HOST
ENV REDIS_PORT=$REDIS_PORT
ENV REDIS_PASSWORD=$REDIS_PASSWORD
ENV PORT=$PORT

WORKDIR /usr/src/app

COPY . .

RUN npm install 

EXPOSE $PORT

CMD ["npm", "start"]